# Generated by Django 2.2.4 on 2019-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_texts_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('fb', 'Facebook'), ('instagram', 'Instagram'), ('tweeter', 'Tweeter'), ('youtube', 'Youtube')], default='fb', max_length=10)),
            ],
        ),
    ]
