from __future__ import unicode_literals

from django.db import migrations
from django.core.files.images import ImageFile
from ..models import News

def create_news(apps, schema_editor):
    News(
        title='Lorem ipsum dolor sit amet 1',
        slug='test-news-1',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 2',
        slug='test-news-2',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 3',
        slug='test-news-3',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 4',
        slug='test-news-4',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 5',
        slug='test-news-5',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 6',
        slug='test-news-6',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 7',
        slug='test-news-7',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 8',
        slug='test-news-8',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 9',
        slug='test-news-9',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 10',
        slug='test-news-10',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 11',
        slug='test-news-11',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 12',
        slug='test-news-12',
        image=ImageFile(open("static/images/image-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();
    News(
        title='Lorem ipsum dolor sit amet 13',
        slug='test-news-13',
        image=ImageFile(open("static/images/carousel-1.jpg", "rb")),
        content="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra sed enim ut ultricies. Donec viverra erat et dolor molestie, vitae suscipit lectus bibendum. Cras placerat eu enim ut porttitor. In hac habitasse platea dictumst. Vestibulum non iaculis turpis. Proin est libero, blandit vitae semper a, fringilla id metus. Cras interdum semper massa, a bibendum nisl eleifend nec. Fusce efficitur, dui ac accumsan scelerisque, ligula leo blandit eros, vel faucibus nisi leo vel eros. Sed sed risus quis velit interdum tempor. Proin diam leo, lacinia at purus ut, sollicitudin porttitor nisl.</p><p>&nbsp;</p><p>Vestibulum maximus lacus elit, non iaculis urna tincidunt eu. Phasellus volutpat justo eu rutrum ornare. Morbi mollis arcu nec mauris vestibulum, pharetra convallis massa finibus. Donec ut lacus sed odio posuere elementum. Vestibulum a dui dui. Ut vestibulum elementum dui, ut malesuada lectus placerat sit amet. Sed augue justo, malesuada nec euismod et, euismod eget mi. Vestibulum non justo at risus semper interdum volutpat ac enim. Nullam venenatis volutpat.</p><p>&nbsp;</p><p>Cras vitae cursus dolor. Aenean ac placerat lectus. Duis et libero volutpat, dapibus nibh at, facilisis lacus. Nulla facilisi. Maecenas sodales tincidunt elementum. Nam ornare auctor arcu sit amet rhoncus. Integer venenatis dolor ut metus gravida imperdiet. Morbi maximus lacus augue, et eleifend enim malesuada et. Nunc ac fermentum orci, vel mollis ligula. Etiam quis blandit nunc. Sed non mi et massa mollis tincidunt ornare eget dolor. Curabitur sit amet ligula sit amet nulla viverra bibendum at sit amet nunc. Aliquam laoreet vitae mi laoreet euismod. Curabitur eu consectetur nunc, id sodales erat. Pellentesque eget ullamcorper diam, a suscipit libero.</p>"
    ).save();


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_news'),
    ]

    operations = [
        migrations.RunPython(create_news)
    ]
